version: '3.7'

x-app-common: &app-common
  build:
    context: ..
    dockerfile: docker/Dockerfile.optimized
  restart: unless-stopped
  networks:
    - app-network
  healthcheck:
    test: ["CMD", "curl", "-f", "--unix-socket", "/run/gunicorn/socket", "http://localhost/api/ping"]
    interval: 30s
    timeout: 3s
    retries: 3
    start_period: 5s
  volumes:
    - ../src:/app
    - ../config/gunicorn.conf.py:/app/gunicorn.conf.py
    - gunicorn-socket:/run/gunicorn

services:
  # Main application
  flask-app:
    <<: *app-common
    container_name: flask_app
    depends_on:
      redis:
        condition: service_healthy
    # Adding Prometheus metrics
    labels:
      - "prometheus.enable=true"
      - "prometheus.port=5000"
      - "prometheus.path=/metrics"

  # Redis database
  redis:
    image: redis:alpine
    container_name: redis_service
    expose:
      - "6379"
    restart: unless-stopped
    volumes:
      - redis-data:/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  # Nginx as a reverse proxy
  nginx:
    image: nginx:alpine
    container_name: flask_proxy
    ports:
      - "80:80"
    volumes:
      - ../config/nginx.conf:/etc/nginx/conf.d/default.conf
      - ../static:/static
      - gunicorn-socket:/run/gunicorn
      - ../docker/fix-permissions.sh:/docker-entrypoint.d/40-fix-permissions.sh
    depends_on:
      flask-app:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "service", "nginx", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Monitoring: Prometheus
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus_service
    ports:
      - "9090:9090"
    volumes:
      - ../config/prometheus.yml:/etc/prometheus/prometheus.yml
    restart: unless-stopped
    depends_on:
      flask-app:
        condition: service_healthy
    networks:
      - app-network

  # Monitoring: Grafana
  grafana:
    image: grafana/grafana:latest
    container_name: grafana_service
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    restart: unless-stopped
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - app-network

  # Redis Exporter for Redis monitoring
  redis-exporter:
    image: oliver006/redis_exporter:latest
    container_name: redis_exporter
    expose:
      - "9121"
    environment:
      - REDIS_ADDR=redis://redis:6379
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - app-network

volumes:
  redis-data:
  grafana-data:
  gunicorn-socket:

networks:
  app-network:
    driver: bridge