version: '3'

services:
  flask-app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - redis
    volumes:
      - ../src:/app

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"