version: '3'

services:
  flask-app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    # Don't publish port externally, only for internal network
    expose:
      - "5000"
    depends_on:
      - redis
    restart: always
    volumes:
      - ../src:/app

  redis:
    image: redis:alpine
    expose:
      - "6379"
    restart: always
    # Adding persistent storage for Redis
    volumes:
      - redis-data:/data

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ../config/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - flask-app
    restart: always

volumes:
  redis-data: