version: '3.8'

services:
  flask-app:
    image: myflaskapp:latest
    build:
      context: ..
      dockerfile: docker/Dockerfile.optimized
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
      restart_policy:
        condition: on-failure
    networks:
      - webnet
    volumes:
      - ../src:/app

  redis:
    image: redis:alpine
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.3'
          memory: 128M
      restart_policy:
        condition: on-failure
    volumes:
      - redis-data:/data
    networks:
      - webnet

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ../config/nginx.conf:/etc/nginx/conf.d/default.conf
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.1'
          memory: 64M
      restart_policy:
        condition: on-failure
    networks:
      - webnet
      
networks:
  webnet:

volumes:
  redis-data: